python_tests_task:
  container:
    image: python:3-alpine
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat pyproject.toml
    populate_script: apk add gcc musl-dev libffi-dev libpq-dev openssl-dev && python3 -m pip install --upgrade poetry && poetry install
  test_script: poetry run python tests

flake8_task:
  container:
    image: alpine/flake8:latest
  script: flake8 --ignore=E128,E261 --max-line-length=120 .

svelte_tests_task:
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  test_script: yarn run test
